/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author LENOVO
 */

import javax.swing.table.DefaultTableModel;
import config.koneksi;
import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


public class MenuDaftarPeminjam extends javax.swing.JPanel {
   

    /**
     * Creates new form MenuDaftarPeminjam
     */
    private final Connection con;
    public MenuDaftarPeminjam() {
       initComponents();
       
       con = koneksi.getConnection();
       setTableModel();
       loadData();
    }

        
        
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(808, 348));
        setLayout(new java.awt.CardLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(808, 348));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Daftar Peminjam Rental PC");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblTransaksi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        getData((DefaultTableModel)tblTransaksi.getModel());
    }

    private void setTableModel() {
        DefaultTableModel model = (DefaultTableModel) tblTransaksi.getModel();
        model.addColumn("ID Transaksi");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("No.Telp");
        model.addColumn("Jenis PC");
        model.addColumn("Durasi Pinjam");
        model.addColumn("Total Harga");
        model.addColumn("Metode Pembayaran");
    }

    private void getData(DefaultTableModel model) {
        model.setRowCount(0);
        
        try {
            String sql = "SELECT * FROM transaksi";
            try (PreparedStatement st = con.prepareStatement(sql)){
              ResultSet rs = st.executeQuery();
              
                while (rs.next()) {
                    String idTransaksi = rs.getString("transaksi_id");
                    String namaPeminjam = rs.getString("nama_peminjam");
                    String alamatPeminjam = rs.getString("alamat");
                    String noTelp = rs.getString("no_telp");
                    String jenisPC = rs.getString("nama_pc");
                    String durasiPinjam = rs.getString("durasi_pinjam");
                    String totalHarga = rs.getString("total_biaya");
                    String metodePembayaran = rs.getString("metode_pembayaran");
                    
                    Object[]rowData ={idTransaksi,namaPeminjam,alamatPeminjam,noTelp,jenisPC,durasiPinjam,totalHarga,metodePembayaran};
                    model.addRow(rowData);
                }
            } 
        } catch (SQLException e) {
            Logger.getLogger(MenuDaftarPeminjam.class.getName()).log(Level.SEVERE,null,e);
        }
        
    }
}
