/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasirentalpc;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import view.MenuDaftarPeminjam;
import view.MenuPC;
import view.MenuTransaksi;

/**
 *
 * @author LENOVO
 */
public class FUtama extends javax.swing.JFrame {

    /**
     * Creates new form FUtama
     */
    public FUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnList = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JLabel();
        btnDaftarPinjam = new javax.swing.JLabel();
        btnLogout = new javax.swing.JLabel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_navbar.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RENTAL PC");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-computer-50.png"))); // NOI18N

        btnList.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnList.setForeground(new java.awt.Color(204, 204, 204));
        btnList.setText("List PC");
        btnList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListMouseExited(evt);
            }
        });

        btnTransaksi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(204, 204, 204));
        btnTransaksi.setText("Transaksi");
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        btnDaftarPinjam.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDaftarPinjam.setForeground(new java.awt.Color(204, 204, 204));
        btnDaftarPinjam.setText("Daftar Peminjam");
        btnDaftarPinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDaftarPinjamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDaftarPinjamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDaftarPinjamMouseExited(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(153, 153, 153));
        btnLogout.setText("Logout");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_navbarLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(btnList)
                        .addGap(77, 77, 77)
                        .addComponent(btnTransaksi)
                        .addGap(69, 69, 69)
                        .addComponent(btnDaftarPinjam)
                        .addContainerGap(158, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_navbarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(40, 40, 40))))
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_navbarLayout.createSequentialGroup()
                .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_navbarLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnList)
                            .addComponent(btnTransaksi)
                            .addComponent(btnDaftarPinjam)))
                    .addGroup(pn_navbarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout)
                            .addComponent(jLabel2))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(102, 102, 102));

        pn_utama.setPreferredSize(new java.awt.Dimension(808, 348));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(pn_dasar, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseExited
        btnList.setForeground(new Color(204,204,204));
        btnList.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnListMouseExited

    private void btnListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseEntered
        btnList.setForeground(Color.YELLOW);
        btnList.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnListMouseEntered

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        btnTransaksi.setForeground(Color.YELLOW);
        btnTransaksi.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        btnTransaksi.setForeground(new Color(204,204,204));
        btnTransaksi.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));      
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnDaftarPinjamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarPinjamMouseEntered
        btnDaftarPinjam.setForeground(Color.YELLOW);
        btnDaftarPinjam.setCursor(new Cursor(Cursor.HAND_CURSOR));      
    }//GEN-LAST:event_btnDaftarPinjamMouseEntered

    private void btnDaftarPinjamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarPinjamMouseExited
        btnDaftarPinjam.setForeground(new Color(204,204,204));
        btnDaftarPinjam.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));    
    }//GEN-LAST:event_btnDaftarPinjamMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        btnLogout.setForeground(Color.RED);
        btnLogout.setCursor(new Cursor(Cursor.HAND_CURSOR));      
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setForeground(new Color(153,153,153));
        btnLogout.setCursor(new Cursor(Cursor.DEFAULT_CURSOR)); 
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseClicked
       btnList.setForeground(new Color(204,204,0));
       
       //btn list saat di klik
       pn_utama.removeAll();
       pn_utama.add(new MenuPC());
       pn_utama.repaint();
       pn_utama.revalidate();
    }//GEN-LAST:event_btnListMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        btnTransaksi.setForeground(new Color(204,204,0));
       
       //btn transaksi saat di klik
       pn_utama.removeAll();
       pn_utama.add(new MenuTransaksi());
       pn_utama.repaint();
       pn_utama.revalidate();
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnDaftarPinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDaftarPinjamMouseClicked
       btnDaftarPinjam.setForeground(new Color(204,204,0));
       
       //btn daftar saat di klik
       pn_utama.removeAll();
       pn_utama.add(new MenuDaftarPeminjam());
       pn_utama.repaint();
       pn_utama.revalidate();
    }//GEN-LAST:event_btnDaftarPinjamMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
       btnLogout.setForeground(new Color(153,0,0));
       
        // Menggunakan JOptionPane untuk konfirmasi logout
       int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin untuk keluar?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);

        // Jika pengguna memilih "Ya" (YES_OPTION)
       if (dialogResult == JOptionPane.YES_OPTION) {
        
        //btn logout saat di klik kembali ke form login
        FLogin loginForm = new FLogin();
        loginForm.setVisible(true);
        dispose();
    }
    // Jika pengguna memilih "Tidak" atau menutup dialog (NO_OPTION atau CLOSE_OPTION), tidak melakukan apa-apa
    }//GEN-LAST:event_btnLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDaftarPinjam;
    private javax.swing.JLabel btnList;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables
}
